CREATE TABLESPACE TS_USUARIOS 
    DATAFILE 'ts_usuarios.dbf'
    SIZE 256M 
    AUTOEXTEND ON NEXT 64M MAXSIZE 4G
    EXTENT MANAGEMENT LOCAL 
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_CATALOGO 
    DATAFILE 'ts_catalogo.dbf'
    SIZE 512M 
    AUTOEXTEND ON NEXT 128M MAXSIZE 8G
    EXTENT MANAGEMENT LOCAL 
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_TRANSACCIONAL 
    DATAFILE 'ts_transaccional.dbf'
    SIZE 256M 
    AUTOEXTEND ON NEXT 64M MAXSIZE 4G
    EXTENT MANAGEMENT LOCAL 
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_ADMIN 
    DATAFILE 'ts_admin.dbf'
    SIZE 128M 
    AUTOEXTEND ON NEXT 32M MAXSIZE 1G
    EXTENT MANAGEMENT LOCAL 
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_IDX 
    DATAFILE 'ts_idx.dbf'
    SIZE 512M 
    AUTOEXTEND ON NEXT 128M MAXSIZE 8G
    EXTENT MANAGEMENT LOCAL 
    SEGMENT SPACE MANAGEMENT AUTO;

-- ------------------------------------------------------------
-- TS_USUARIOS
-- ------------------------------------------------------------
ALTER TABLE PLANES          MOVE TABLESPACE TS_USUARIOS;
ALTER TABLE ROLES_USUARIO   MOVE TABLESPACE TS_USUARIOS;
ALTER TABLE USUARIOS        MOVE TABLESPACE TS_USUARIOS;
ALTER TABLE PERFILES        MOVE TABLESPACE TS_USUARIOS;
ALTER TABLE PAGOS           MOVE TABLESPACE TS_USUARIOS;
ALTER TABLE HISTORIAL_PLANES MOVE TABLESPACE TS_USUARIOS;

-- ------------------------------------------------------------
-- TS_CATALOGO
-- ------------------------------------------------------------
ALTER TABLE CATEGORIAS          MOVE TABLESPACE TS_CATALOGO;
ALTER TABLE GENEROS             MOVE TABLESPACE TS_CATALOGO;
ALTER TABLE CONTENIDO           MOVE TABLESPACE TS_CATALOGO;
ALTER TABLE CONTENIDO_GENEROS   MOVE TABLESPACE TS_CATALOGO;
ALTER TABLE CONTENIDO_RELACIONADO MOVE TABLESPACE TS_CATALOGO;
ALTER TABLE TEMPORADAS          MOVE TABLESPACE TS_CATALOGO;
ALTER TABLE EPISODIOS           MOVE TABLESPACE TS_CATALOGO;

-- ------------------------------------------------------------
-- TS_TRANSACCIONAL
-- ------------------------------------------------------------
ALTER TABLE CALIFICACIONES        MOVE TABLESPACE TS_TRANSACCIONAL;
ALTER TABLE FAVORITOS             MOVE TABLESPACE TS_TRANSACCIONAL;
ALTER TABLE REPORTES_INAPROPIADO  MOVE TABLESPACE TS_TRANSACCIONAL;

-- ------------------------------------------------------------
-- TS_ADMIN
-- ------------------------------------------------------------
ALTER TABLE ROLES               MOVE TABLESPACE TS_ADMIN;
ALTER TABLE DEPARTAMENTOS       MOVE TABLESPACE TS_ADMIN;
ALTER TABLE EMPLEADOS           MOVE TABLESPACE TS_ADMIN;
ALTER TABLE REFERIDOS           MOVE TABLESPACE TS_ADMIN;
ALTER TABLE BENEFICIOS_REFERIDOS MOVE TABLESPACE TS_ADMIN;
