-- ============================================================
-- QUINDIOFLIX — Nucleo 4: Seguridad (CORREGIDO)
-- ============================================================

-- 1. CREACIÓN DE ROLES
CREATE ROLE ROL_ADMIN;
CREATE ROLE ROL_ANALISTA;
CREATE ROLE ROL_SOPORTE;
CREATE ROLE ROL_CONTENIDO;

-- 2. PERFIL DE RECURSOS
CREATE PROFILE PERFIL_QUINDIOFLIX LIMIT
    SESSIONS_PER_USER         3
    IDLE_TIME                 30
    CONNECT_TIME              480
    FAILED_LOGIN_ATTEMPTS     5
    PASSWORD_LOCK_TIME        1
    PASSWORD_LIFE_TIME        90
    PASSWORD_GRACE_TIME       7
    PASSWORD_REUSE_TIME       365
    PASSWORD_REUSE_MAX        5
    CPU_PER_SESSION           1000
    LOGICAL_READS_PER_SESSION 1000000
    PRIVATE_SGA               50M;


-- Usuario Administrador
CREATE USER admin_quindio IDENTIFIED BY "Admin2026!"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;
ALTER USER admin_quindio PROFILE PERFIL_QUINDIOFLIX;

-- Usuario Analista
CREATE USER analista_quindio IDENTIFIED BY "Analista2026!"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA 100M ON USERS;
ALTER USER analista_quindio PROFILE PERFIL_QUINDIOFLIX;

-- Usuario Soporte
CREATE USER soporte_quindio IDENTIFIED BY "Soporte2026!"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA 50M ON USERS;
ALTER USER soporte_quindio PROFILE PERFIL_QUINDIOFLIX;

-- Usuario Gestor de Contenido
CREATE USER contenido_quindio IDENTIFIED BY "Contenido2026!"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA 200M ON USERS;
ALTER USER contenido_quindio PROFILE PERFIL_QUINDIOFLIX;

COMMIT;

-- 4. ASIGNACIÓN DE PRIVILEGIOS A ROLES (versión resumida y funcional)
-- ROL_ADMIN
GRANT CREATE SESSION TO ROL_ADMIN;
GRANT CREATE USER, ALTER USER, DROP USER TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PLANES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON USUARIOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PERFILES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PAGOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONTENIDO TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CATEGORIAS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENEROS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON TEMPORADAS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON EPISODIOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON REPRODUCCIONES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CALIFICACIONES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON FAVORITOS TO ROL_ADMIN;
GRANT EXECUTE ON SP_REGISTRAR_USUARIO TO ROL_ADMIN;
GRANT EXECUTE ON SP_CAMBIAR_PLAN TO ROL_ADMIN;
GRANT EXECUTE ON SP_REPORTE_CONSUMO TO ROL_ADMIN;

-- ROL_ANALISTA
GRANT CREATE SESSION TO ROL_ANALISTA;
GRANT SELECT ON PLANES TO ROL_ANALISTA;
GRANT SELECT ON USUARIOS TO ROL_ANALISTA;
GRANT SELECT ON PERFILES TO ROL_ANALISTA;
GRANT SELECT ON PAGOS TO ROL_ANALISTA;
GRANT SELECT ON CONTENIDO TO ROL_ANALISTA;
GRANT SELECT ON CATEGORIAS TO ROL_ANALISTA;
GRANT SELECT ON GENEROS TO ROL_ANALISTA;
GRANT SELECT ON TEMPORADAS TO ROL_ANALISTA;
GRANT SELECT ON EPISODIOS TO ROL_ANALISTA;
GRANT SELECT ON REPRODUCCIONES TO ROL_ANALISTA;
GRANT SELECT ON CALIFICACIONES TO ROL_ANALISTA;
GRANT EXECUTE ON SP_REPORTE_CONSUMO TO ROL_ANALISTA;

-- ROL_SOPORTE
GRANT CREATE SESSION TO ROL_SOPORTE;
GRANT SELECT ON USUARIOS TO ROL_SOPORTE;
GRANT SELECT ON PERFILES TO ROL_SOPORTE;
GRANT SELECT ON PAGOS TO ROL_SOPORTE;
GRANT SELECT ON PLANES TO ROL_SOPORTE;
GRANT SELECT ON HISTORIAL_PLANES TO ROL_SOPORTE;
GRANT INSERT, UPDATE ON PAGOS TO ROL_SOPORTE;
GRANT EXECUTE ON SP_CAMBIAR_PLAN TO ROL_SOPORTE;

-- ROL_CONTENIDO
GRANT CREATE SESSION TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONTENIDO TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON CATEGORIAS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENEROS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON TEMPORADAS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON EPISODIOS TO ROL_CONTENIDO;
GRANT SELECT ON REPRODUCCIONES TO ROL_CONTENIDO;
GRANT SELECT ON CALIFICACIONES TO ROL_CONTENIDO;

-- 5. ASIGNACIÓN DE ROLES A USUARIOS
GRANT ROL_ADMIN TO admin_quindio;
GRANT ROL_ANALISTA TO analista_quindio;
GRANT ROL_SOPORTE TO soporte_quindio;
GRANT ROL_CONTENIDO TO contenido_quindio;

COMMIT;

-- 6. VERIFICACIÓN
SELECT username, account_status FROM dba_users WHERE username LIKE '%QUINDIO';
SELECT grantee, granted_role FROM dba_role_privs WHERE grantee LIKE '%QUINDIO';